# Generated by Django 5.0.1 on 2024-01-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=20, null=True)),
                ('descreption', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='features_product',
            fields=[
                ('featuresproduct_id', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=20, null=True)),
                ('descreption', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=20, null=True)),
                ('review', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('descreption', models.CharField(blank=True, max_length=200, null=True)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('new_price', models.IntegerField(blank=True, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
