# Generated by Django 5.0.1 on 2024-01-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customer_card_number_customer_cardholder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_founder',
            fields=[
                ('id', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_contact',
            fields=[
                ('contact_id', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('messege', models.IntegerField(blank=True, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
